### ISSUE TITLE
mzapy functions hang when requesting XIC or scan

### ISSUE THREAD

**Issue by wkumler** [PNNL-m-q/mzapy#26]
Hi again, I'm still trying to follow along with the tech note demo with my own MZA file but I've run into problems when I try to request an XIC or scan m/z & intensity data. When I run the below code in a Jupyter notebook, it throws an error (`KeyError: 'Unable to synchronously open object (component not found)'`) and hangs indefinitely. This is the case with both `collect_ms1_arrays_by_rt` and `collect_xic_arrays_by_mz`. Other methods seem to work fine (e.g. `mza.min_rt` causes no problems) so it seems like it's just the arrays that are the issue.

```python
import mzapy
import h5py
```

```python
mza=mzapy.MZA("../demo_data/180205_Poo_TruePoo_Full1.mza")
```

```python
xic_rt, xic_i = mza.collect_xic_arrays_by_mz(118.08, 118.10)
```

I'm running this in a Jupyter notebook and getting a kinda bizarre thing happening where the imports and mza variable cells work perfectly, but when I run the XIC cell an error shows up in the mza definition cell?? The XIC cell then seems to hang and be "calculating" basically indefinitely. The same thing happens when I try to get a single scan:

```python
mza.collect_ms1_arrays_by_rt(0, 0.01)
```

I'm using the `no_full_mz_array` branch since I'm working on Orbitrap data. The MZA file I'm using is available [here](https://github.com/wkumler/mzsql/blob/master/demo_data/180205_Poo_TruePoo_Full1.mza) and the Jupyter notebook is [here](https://github.com/wkumler/mzsql/blob/master/demo_notebooks/mza_notebook.ipynb). Any recommendations for how to get around this? I'll try leaving the XIC extraction code running even longer in the meantime.

**Comment by dylanhross** [comment]
There was a problem with some of the threaded IO under the hood. Seems to be fixed now. Attaching short example with your test file for reference. 

[test.pdf](https://github.com/user-attachments/files/17837224/test.pdf)

**Comment by wkumler** [comment]
Awesome! Successfully built 1.8.0.dev4 and can run all the necessary functions. Thanks a bunch!
